### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/account-invoicing#37]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_clean_cancelled_invoice_number
- [ ] account_invoice_change_currency
- [ ] account_invoice_commercial
- [ ] account_invoice_commission
- [ ] account_invoice_company_search
- [ ] account_invoice_control
- [ ] account_invoice_journal_group
- [ ] account_invoice_line_number
- [ ] account_invoice_move_currency
- [ ] account_invoice_operation
- [ ] account_invoice_pay_directly
- [ ] account_invoice_prices_update
- [ ] account_invoice_tax_wizard
- [ ] account_partner_restrict_invoicing
- [ ] account_user_default_journals
- [ ] website_sale_account_invoice_commission
