### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/account-invoicing#85]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] account_invoice_prices_update
- [ ] account_invoice_control
- [ ] account_clean_cancelled_invoice_number
- [ ] account_invoice_partial
- [ ] account_invoice_commission
- [ ] website_sale_account_invoice_commission
- [ ] account_invoice_move_currency
- [ ] account_invoice_line_number
